# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: kubectl
      version: 1.34.1
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/kubectl:1.34.1-debian-12-r3
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
    - name: redis
      version: 8.2.3
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/redis:8.2.3-debian-12-r0
    - name: redis-exporter
      version: 1.79.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/redis-exporter:1.79.0-debian-12-r0
    - name: redis-sentinel
      version: 8.2.3
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/redis-sentinel:8.2.3-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.2.3
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Redis(R) is an open source, advanced key-value store. It is often referred
  to as a data structure server since keys can contain strings, hashes, lists, sets
  and sorted sets.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: redis
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/redis
version: 23.2.2
