# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
    - name: thanos
      version: 0.40.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/thanos:0.40.0-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 0.40.0
dependencies:
- condition: minio.enabled
  name: minio
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 17.x.x
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Thanos is a highly available metrics system that can be added on top
  of existing Prometheus deployments, providing a global query view across all Prometheus
  installations.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/thanos/img/thanos-stack-220x234.png
keywords:
- analytics
- monitoring
- prometheus
- thanos
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: thanos
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/thanos
version: 17.4.1
