# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: kubectl
      version: 1.34.1
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/kubectl:1.34.1-debian-12-r3
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
    - name: redis-exporter
      version: 1.79.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/redis-exporter:1.79.0-debian-12-r0
    - name: valkey
      version: 9.0.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/valkey:9.0.0-debian-12-r0
    - name: valkey-sentinel
      version: 9.0.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/valkey-sentinel:9.0.0-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 9.0.0
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Valkey is an open source (BSD) high-performance key/value datastore that
  supports a variety workloads such as caching, message queues, and can act as a primary
  database.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
keywords:
- valkey
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: valkey
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/valkey
version: 5.0.0
