# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: jenkins
      version: 2.528.1
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/jenkins:2.528.1-debian-12-r0
    - name: jenkins-agent
      version: 0.3345.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/jenkins-agent:0.3345.0-debian-12-r0
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 2.528.1
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Jenkins is an open source Continuous Integration and Continuous Delivery
  (CI/CD) server designed to automate the building, testing, and deploying of any
  software project.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/jenkins/img/jenkins-stack-220x234.png
keywords:
- jenkins
- ci
- cd
- http
- web
- application
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: jenkins
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/jenkins
version: 13.7.0
