# Copyright 2025 SolDevelo
# Based on Bitnami Kafka Helm Chart © Broadcom, Inc. (Apache-2.0)
# SPDX-License-Identifier: Apache-2.0

annotations:
  images: |
    - name: jmx-exporter
      image: docker.io/soldevelo/jmx-exporter:1.4.0
    - name: kafka
      image: docker.io/soldevelo/kafka:4.0.0
    - name: kubectl
      image: docker.io/soldevelo/kubectl:1.33.4
    - name: os-shell
      image: docker.io/soldevelo/os-shell:12-r51
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 4.0.0
dependencies:
- name: common-chart
  repository: oci://registry-1.docker.io/soldevelo
  tags:
  - soldevelo-common
  version: 2.x.x
description: Apache Kafka is a distributed streaming platform designed to build real-time
  pipelines and can be used as a message broker or as a replacement for a log aggregation
  solution for big data applications.
home: https://soldevelo.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/kafka/img/kafka-stack-220x234.png
keywords:
- kafka
- streaming
- producer
- consumer
maintainers:
- name: SolDevelo
  url: https://github.com/soldevelo/charts
name: kafka-chart
sources:
- https://github.com/soldevelo/charts/tree/main/soldevelo/kafka
version: 32.4.4
