# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: cassandra
      version: 5.0.5
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/cassandra:5.0.5-debian-12-r23
    - name: jaeger
      version: 2.11.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/jaeger:2.11.0-debian-12-r2
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 2.11.0
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
- condition: cassandra.enabled
  name: cassandra
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 12.x.x
description: Jaeger is a distributed tracing system. It is used for monitoring and
  troubleshooting microservices-based distributed systems.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/jaeger/img/jaeger-stack-220x234.png
keywords:
- jaeger
- tracing
- monitoring
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: jaeger
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/jaeger
version: 6.1.0
