# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: neo4j
      version: 5.26.15
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/neo4j:5.26.15-debian-12-r0
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 5.26.15
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Neo4j is a high performance graph store with all the features expected
  of a mature and robust database, like a friendly query language and ACID transactions.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/neo4j/img/neo4j-stack-220x234.png
keywords:
- database
- neo4j
- graph
- graphdb
- graph-database
- nosql
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: neo4j
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/neo4j
- https://github.com/bitnami/containers/tree/main/bitnami/neo4j
- https://github.com/neo4j/neo4j
version: 0.6.3
