# Copyright 2025 SolDevelo
# Based on Bitnami Common Helm Chart © Broadcom, Inc. (Apache-2.0)
# SPDX-License-Identifier: Apache-2.0

annotations:
  licenses: Apache-2.0
apiVersion: v2
# Please make sure that version and appVersion are always the same.
appVersion: 2.31.7
description: A Library Helm Chart for grouping common logic between Soldevelo charts. This chart is not deployable by itself.
home: https://soldevelo.com
icon: https://soldevelo.com/wp-content/uploads/2023/04/cropped-Frame-180x37.png
keywords:
  - common
  - helper
  - template
  - function
  - soldevelo
maintainers:
  - name: SolDevelo
    url: https://github.com/soldevelo/charts
name: common-chart
sources:
  - https://github.com/soldevelo/charts/tree/main/soldevelo/common
type: library
version: 2.31.7
