# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: gitea
      version: 1.24.6
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/gitea:1.24.6-debian-12-r5
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 1.24.6
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 18.x.x
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Gitea is a lightweight code hosting solution. Written in Go, features
  low resource consumption, easy upgrades and multiple databases.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/gitea/img/gitea-stack-220x234.png
keywords:
- gitea
- analytics
- http
- web
- application
- php
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: gitea
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/gitea
version: 4.1.0
