{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.sensitiveProps.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-sensitive-props" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: nifi
    app.kubernetes.io/component: nifi
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  sensitive-props-key: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-sensitive-props" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-") "key" "password" "length" 16 "providedValues" (list "sensitiveProps.key") "context" $) }}
{{- end }}
