# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: apache-exporter
      version: 1.0.11
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/apache-exporter:1.0.11-debian-12-r0
    - name: moodle
      version: 5.1.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/moodle:5.1.0-debian-12-r3
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 5.1.0
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 22.x.x
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Moodle(TM) LMS is an open source online Learning Management System widely
  used at universities, schools, and corporations. It is modular and highly adaptable
  to any type of online learning.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/moodle/img/moodle-stack-220x234.png
keywords:
- moodle
- learning
- php
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: moodle
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/moodle
version: 29.0.4
