# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: node-exporter
      version: 1.10.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/node-exporter:1.10.0-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 1.10.0
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Prometheus exporter for hardware and OS metrics exposed by UNIX kernels,
  with pluggable metric collectors.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/node-exporter/img/node-exporter-stack-220x234.png
keywords:
- prometheus
- node-exporter
- monitoring
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: node-exporter
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/node-exporter
version: 4.6.1
