# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: apache-exporter
      version: 1.0.11
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/apache-exporter:1.0.11-debian-12-r0
    - name: matomo
      version: 5.5.1
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/matomo:5.5.1-debian-12-r0
    - name: os-shell
      version: "12"
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/os-shell:12-debian-12-r53
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 5.5.1
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  version: 22.x.x
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Matomo, formerly known as Piwik, is a real time web analytics program.
  It provides detailed reports on website visitors.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/matomo/img/matomo-stack-220x234.png
keywords:
- matomo
- analytics
- http
- web
- application
- php
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: matomo
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/matomo
version: 11.1.1
