# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  fips: "false"
  images: |
    - name: metrics-server
      version: 0.8.0
      image: registry.app-catalog.vmware.com/eam/prd/containers/verified/common/minideb-bookworm/metrics-server:0.8.0-debian-12-r9
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 0.8.0
dependencies:
- name: common
  repository: oci://registry.app-catalog.vmware.com/eam/prd/charts/verified/common/minideb-bookworm
  tags:
  - bitnami-common
  version: 2.x.x
description: Metrics Server aggregates resource usage data, such as container CPU
  and memory usage, in a Kubernetes cluster and makes it available via the Metrics
  API.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/metrics-server/img/metrics-server-stack-220x234.png
keywords:
- metrics-server
- cluster
- metrics
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: metrics-server
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/metrics-server
version: 7.5.0
